Repository adaros92/CS467-Project, pull requests merged in 2020-12, with the labels that each got.

#24 adding a -mp --model_path as an argument
  genreml/model/__main__.py
Labels: new-feature

#25 Feature/cli predictions
  .gitignore
  README.md
  docs/Music_Genre_Classification.ipynb
  genreml/model/__main__.py
  genreml/model/acquisition/config.py
  genreml/model/acquisition/extraction.py
  genreml/model/acquisition/youtube.py
  genreml/model/cnn/cnn.py
  genreml/model/cnn/config.py
  genreml/model/cnn/data/feature_cols.csv
  genreml/model/cnn/data/labels_key.csv
  genreml/model/cnn/data/std_scaler_B.pkl
  genreml/model/model/base_model.py
  genreml/model/model/input.py
  genreml/model/processing/audio.py
  genreml/model/utils/file_handling.py
  genreml/model/utils/model_utils.py
  setup.py
  test/test_classification.py
  test/test_cli.py
Labels: enhancement, new-feature

#29 Update setup.py
  MANIFEST.ini
  setup.py
Labels: bug
