Repository adaros92/CS467-Project, pull requests merged in 2020-11, with the labels that each got.

#10 Add feature extraction capabilities to CLI
  README.md
  install.sh
  src/model/__main__.py
  src/model/processing/audio.py
  src/model/processing/audio_features.py
  src/model/processing/config.py
  src/model/utils/file_handling.py
  src/model/utils/string_parsing.py
  src/setup.py
Labels: documentation, new-feature

#11 Create pypi deployable package
  MANIFEST.ini
  README.md
  deploy.sh
  genreml/__init__.py
  genreml/fma_data/000002.mp3
  genreml/fma_data/000005.mp3
  genreml/fma_data/000010.mp3
  genreml/fma_data/000140.mp3
  genreml/fma_data/000141.mp3
  genreml/fma_data/000148.mp3
  genreml/fma_data/000182.mp3
  genreml/fma_data/000190.mp3
  genreml/fma_data/000193.mp3
  genreml/fma_data/000194.mp3
  genreml/fma_data/000197.mp3
  genreml/fma_data/000200.mp3
  genreml/model/__init__.py
  genreml/model/__main__.py
  genreml/model/cnn/__init__.py
  genreml/model/processing/__init__.py
  genreml/model/processing/audio.py
  genreml/model/processing/audio_features.py
  genreml/model/processing/config.py
  genreml/model/processing/extraction.py
  genreml/model/utils/__init__.py
  genreml/model/utils/file_handling.py
  genreml/model/utils/logger.py
  genreml/model/utils/string_parsing.py
  genreml/webapp/__init__.py
  genreml/webapp/frontend/Dockerfile
  genreml/webapp/frontend/README.md
  genreml/webapp/frontend/__init__.py
  genreml/webapp/frontend/app.py
  genreml/webapp/frontend/static/style.css
  genreml/webapp/frontend/templates/index.html
  genreml/webapp/frontend/templates/layout.html
  genreml/webapp/v0.1prototype/__init__.py
  genreml/webapp/v0.1prototype/run_webapp.sh
  genreml/webapp/v0.1prototype/setup.py
  genreml/webapp/v0.1prototype/static/style.css
  genreml/webapp/v0.1prototype/templates/index.html
  genreml/webapp/v0.1prototype/templates/layout.html
  genreml/webapp/v0.1prototype/views.py
  install.sh
  setup.cfg
  setup.py
  src/setup.py
  test/test_file_handling.py
  uninstall.sh
Labels: documentation, enhancement

#12 Add basic unit tests
  .gitignore
  deploy.sh
  genreml/fma_data/000141.mp3
  genreml/fma_data/000148.mp3
  genreml/fma_data/000182.mp3
  genreml/fma_data/000190.mp3
  genreml/fma_data/000193.mp3
  genreml/fma_data/000194.mp3
  genreml/fma_data/000197.mp3
  genreml/fma_data/000200.mp3
  genreml/fma_data/001039.mp3
  genreml/fma_data/001040.mp3
  genreml/fma_data/001066.mp3
  genreml/fma_data/001069.mp3
  genreml/fma_data/001073.mp3
  genreml/fma_data/001075.mp3
  genreml/fma_data/001082.mp3
  genreml/fma_data/001083.mp3
  genreml/model/processing/audio.py
  install.sh
  run_tests.sh
  setup.py
  test/test_cli.py
  test/test_config.py
  test/test_feature_extraction.py
  test/test_file_handling.py
  test/test_string_parsing.py
  uninstall.sh
Labels: new-feature

#13 Add waveplot, spectrogram, melspectrogram, and chromogram generation
  README.md
  aws_infrastructure/genreml-cloudformation-template.yml
  genreml/model/__main__.py
  genreml/model/processing/audio.py
  genreml/model/processing/audio_features.py
  genreml/model/processing/config.py
  genreml/model/processing/display.py
  test/test_feature_extraction.py
  uninstall.sh
Labels: enhancement, new-feature

#14 Fix bug with mfcc feature aggregation; remove youtube_dl; return name…
  genreml/model/__main__.py
  genreml/model/processing/audio.py
  genreml/model/processing/audio_features.py
  genreml/model/processing/extraction.py
  setup.py
Labels: bug

#16 Fixing feature_name naming in feature extraction
  genreml/model/processing/audio_features.py
Labels: bug

#18 classifier test script & QOL improvments
  .gitignore
  audio_classifier/audio-classifier.py
  audio_classifier/classifier_test.py
  audio_classifier/requirements.txt
Labels: enhancement, new-feature

#17 Add capability to generate and store visual features without saving
  README.md
  deploy.sh
  genreml/model/processing/audio.py
  install.sh
  setup.py
Labels: new-feature

#20 Add capability to run feature extraction from raw audio data rather t…
  README.md
  genreml/model/processing/audio.py
  run_tests.sh
  test/test_feature_extraction.py
Labels: enhancement

#21 Working prod deployment of simple webapp to display visual features
  MANIFEST.ini
  README.md
  deploy_genreml.sh
  deploy_webapp.sh
  genreml/model/__main__.py
  genreml/model/acquisition/__init__.py
  genreml/model/acquisition/config.py
  genreml/model/acquisition/extraction.py
  genreml/model/acquisition/request.py
  genreml/model/acquisition/youtube.py
  genreml/model/cnn/cnn.py
  genreml/model/cnn/config.py
  genreml/model/cnn/utils.py
  genreml/model/model/__init__.py
  genreml/model/model/base_model.py
  genreml/model/model/input.py
  genreml/model/processing/audio.py
  genreml/model/processing/config.py
  genreml/model/utils/multithreading.py
  genreml/model_resources/feature_cols.csv
  genreml/model_resources/labels_key.csv
  genreml/webapp/frontend/Dockerfile
  genreml/webapp/frontend/README.md
  genreml/webapp/frontend/app.py
  genreml/webapp/frontend/templates/index.html
  genreml/webapp/v0.1prototype/__init__.py
  genreml/webapp/v0.1prototype/run_webapp.sh
  genreml/webapp/v0.1prototype/setup.py
  genreml/webapp/v0.1prototype/static/style.css
  genreml/webapp/v0.1prototype/templates/index.html
  genreml/webapp/v0.1prototype/templates/layout.html
  genreml/webapp/v0.1prototype/views.py
  setup.py
  test/test_config.py
  test/test_multithreading_utils.py
  webapp/__init__.py
  webapp/frontend/__init__.py
  webapp/frontend/processing/__init__.py
  webapp/frontend/processing/feature_extraction.py
  webapp/frontend/processing/genre_prediction.py
  webapp/frontend/requirements.txt
  webapp/frontend/static/style.css
  webapp/frontend/templates/index.html
  webapp/frontend/templates/layout.html
  webapp/frontend/templates/results.html
  webapp/frontend/views.py
Labels: new-feature, web-app

#22 Add youtube downloader on site
  genreml/model/acquisition/extraction.py
  genreml/model/acquisition/youtube.py
  genreml/model/utils/file_handling.py
  setup.py
  webapp/frontend/processing/downloader.py
  webapp/frontend/processing/feature_extraction.py
  webapp/frontend/requirements.txt
  webapp/frontend/templates/index.html
  webapp/frontend/views.py
Labels: new-feature, web-app

#23 Feature/model builder
  .gitignore
  fma_model_builder/build_model.py
  fma_model_builder/custom_model.py
  fma_model_builder/data/labels_key.csv
  fma_model_builder/dataset_config.py
  genreml/model/cnn/cnn.py
  genreml/model/cnn/dataset.py
  genreml/model/model/base_model.py
  setup.py
Labels: enhancement, new-feature
